### ISSUE TITLE
Need to be able to get many attributes at same level

### ISSUE THREAD

**Issue by mathix420** [pulsar-inc/scrapito#2]
exemple:

```yaml
pipelines:
  - name: players
    url: ...
   extract:
     - name: name
       attribute: $text
     - name: link
       attribute: href
```

result:

```json
"players": [
    { "name": "player1", "url": "url1" },
    { "name": "player2", "url": "url2" }
]
```
